# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assets}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Dempsey"]
  s.date = %q{2010-09-28}
  s.description = %q{Assets is a simple gem that provides an ActiveRecord model that handles attachments via paperclip, 
                        and provides additional helpful and often common functionality}
  s.email = %q{jack.dempsey@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "assets.gemspec",
     "lib/assets.rb",
     "lib/generators/assets_builder/install_generator.rb",
     "lib/generators/assets_builder/templates/migration.rb",
     "spec/assets_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "writeme.yml"
  ]
  s.homepage = %q{http://github.com/jackdempsey/assets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{small layer that sits on top of paperclip and provides some conveniences}
  s.test_files = [
    "spec/assets_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, ["~> 2.3.3"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
    else
      s.add_dependency(%q<paperclip>, ["~> 2.3.3"])
      s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
    end
  else
    s.add_dependency(%q<paperclip>, ["~> 2.3.3"])
    s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
  end
end

